package controller;

public enum MenuCommands {
	APP_QUIT, SHOW_LIST_WAREHOUSE, SHOW_DETAIL_WAREHOUSE, ADD_WAREHOUSE, DELETE_WAREHOUSE
	, SHOW_LIST_PARTS, SHOW_DETAIL_PARTS, ADD_PARTS, DELETE_PARTS, ADD_INVENTORY, DELETE_INVENTORY
	, SHOW_DETAIL_INVENTORY, SHOW_LIST_INVENTORY
	, SHOW_LOGOUT,SHOW_LOGIN,SHOW_LIST_USERS,SHOW_DETAIL_USER,ADD_USER,DELETE_USER 
	, REPORT_PDF, REPORT_EXCEL
}
